In [5]:
import pandas as pd
import seaborn as sns
import os
import matplotlib.pyplot as plt
import numpy as np

In [7]:
dfs = []
for file in os.listdir("data/downloads/drive"):
    xlsx = pd.read_excel(f"data/downloads/drive/{file}", parse_dates=["AppointmentDate"])
    dfs.append(xlsx)
data = pd.concat(dfs)

/var/folders/px/ghnvmq4s27bfdyj3nmvj5bgm0000gn/T/ipykernel_75565/2310853714.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat(dfs)

In [18]:
print(len(data))
temp = data.drop_duplicates()
print(len(temp))

5913
5681

In [19]:
data.loc[data.duplicated()]

,Chart#,LastName,FirstName,Age,PatientDOB,Gender,AppointmentDate,Time,AppointmentType,Reason,CRDPROG CPT,CRDPROG CPT Count
0,3693,JONES,MARK,58,1966-01-04,M,2024-10-30,02:20 AM,HPD DAY 2,C@1100_________________REVO/MOD,NaN,NaN
1,1221,TAULMAN,BRIAN SCOTT,59,1964-12-29,M,2024-10-30,03:25 AM,HPD DAY 2,C@0800_________________THEFT4,['CBEOH'],1.0
2,3709,FLYNN,JON,68,1955-12-20,M,2024-10-30,04:00 AM,HPD CRD,RPI--------------------**SEXASSAULT3,"['NBMHS', 'NCAGE']",2.0
3,3710,LUDWIG,TERSON,48,1975-12-02,M,2024-10-30,04:05 AM,HPD CRD,**HABITUAL OVUII CRIM CONTMPT DRIV-LIC REVOKE,"['NBMHS', 'NCAGE']",2.0
4,3016,CALARA,ENRICO,55,1969-03-10,M,2024-10-30,04:10 AM,HPD CRD,**##ABUSE,['PEMHC'],1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29,270,DAVIS,KENNETH,24,2000-03-31,M,2024-10-30,06:35 AM,HPD CRD,DISORDERLY CONDUCT REFUSAL TO PROVIDE ID CONTE...,"['RBMHS', 'RCAGE']",2.0
30,650,SMITH,JOSIAH,24,2000-01-01,M,2024-10-30,06:40 AM,HPD CRD,HARASSMENT,"['PEMHC', 'RBMHS', 'RCAGE']",3.0
31,3726,WOODS,WILLIE,44,1980-04-05,M,2024-10-30,06:45 AM,HPD CRD,ABUSE FM,"['NBMHS', 'NCAGE']",2.0
32,3727,MATSUNAGA,JOSHUA,26,1998-05-01,M,2024-10-30,06:50 AM,HPD CRD,ASSAULT3,"['NBMHS', 'NCAGE']",2.0
2,1109,AKAU,LANDON,29,1995-03-17,M,2024-07-02,01:20 AM,HPD DAY 2,Abuse Family,NaN,NaN

In [20]:
data["Chart#"].nunique()

3119

In [16]:
data["AppointmentType"].unique()

array(['HPD DAY 2', 'HPD CRD', 'HPD DAY 3', 'HPD DAY 4', 'HPD DAY 5',
       'HPD DAY 6 OR &gt;'], dtype=object)

In [17]:
data.loc[
    (data["AppointmentDate"] >= pd.to_datetime("2024-04-01"))
    & (data["AppointmentDate"] <= pd.to_datetime("2024-10-01"))
    & (data["AppointmentType"] == "HPD CRD")
]

,Chart#,LastName,FirstName,Age,PatientDOB,Gender,AppointmentDate,Time,AppointmentType,Reason,CRDPROG CPT,CRDPROG CPT Count
4,1970,SLIPPEY,QUINCY,44,1980-08-10,M,2024-08-08,03:25 AM,HPD CRD,C@8--------PRO RESISTING ARREST,"['RBMHS', 'RCAGE']",2.0
5,1971,LEE,EUN YOUNG,53,1971-08-08,F,2024-08-08,03:30 AM,HPD CRD,CONTEMPTX2,"['NBMHS', 'NCAGE']",2.0
6,1972,CLOCK,RICHARD,54,1969-09-13,M,2024-08-08,03:35 AM,HPD CRD,DISORDERLY CONDUCT,"['RBMHS', 'RCAGE']",2.0
7,1973,ORIVE,ERNESTO,41,1983-03-12,M,2024-08-08,03:40 AM,HPD CRD,CONTEMPTX4,"['NBMHS', 'NCAGE']",2.0
8,1691,REID,JORDAN,35,1989-01-25,M,2024-08-08,03:55 AM,HPD CRD,THEFT4 DANG3,"['NBMHS', 'NCAGE']",2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
44,72,MIN,GEOFFREY,31,1992-08-30,M,2024-07-02,03:55 AM,HPD CRD,**DANG3 INDECENT,"['CBPLY', 'RBMHS', 'RCAGE']",3.0
45,1138,KUNUSEM,AMINTON,20,2004-01-26,M,2024-07-02,04:00 AM,HPD CRD,**THEFT4,"['RBMHS', 'RCAGE']",2.0
46,1139,ROBINSON,REEF,20,2004-03-02,M,2024-07-02,04:05 AM,HPD CRD,Reckless Driving Obedience to PO Det Drug 2,"['NBMHS', 'NCAGE']",2.0
48,1118,HWANG,ILAE,39,1985-02-09,M,2024-07-02,08:15 AM,HPD CRD,**OVUII PM,"['NBMHS', 'NCAGE']",2.0
49,1125,ALBARADO,ZACHERY,47,1977-02-23,M,2024-07-02,08:55 AM,HPD CRD,OVUII/PRO DANG Drug,"['NBMHS', 'NCAGE']",2.0